config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'events/index'
  get 'events/new'
  get 'events/create'
  get 'events/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "sessions#new"
  resources :students, only: [:index, :new, :create] do
    member do
      get :attendance
    end
  end
  resources :events, only: [:index, :new, :create, :show]  do
    member do
      get :attendees
    end
  end

  # Custom routes for specific actions if needed
  get 'students/:id/attendance', to: 'students#attendance', as: 'student_attendance'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :event_attendances, dependent: :destroy
    has_many :students, through: :event_attendances
  
    validates :name, presence: true
    validates :date, presence: true
  end
  

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :student
  belongs_to :event

  validates :attended_on, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :event_attendances
    has_many :events, through: :event_attendances
  
    validates :email, presence: true, uniqueness: true
    validates :name, presence: true
    validates :year, presence: true
  
    before_create :initialize_attendance_points
  
    private

    def self.search(query)
      where("name LIKE ? OR email LIKE ? OR major LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
    end
  
    def initialize_attendance_points
      self.attendance_points ||= 1
    end
  end
  

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def require_login
      unless current_user
        flash[:alert] = "You must be logged in to access this section"
        redirect_to login_path
      end
    end
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path, notice: 'Event created successfully.'
    else
      render :new
    end
  end

  
  def show
    @event = Event.find(params[:id])
    @attendees = @event.students
  end

  private

  def event_params
    params.require(:event).permit(:name, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to students_path, notice: "Logged in successfully"
    else
      flash.now[:alert] = "Invalid username or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out successfully"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    # before_action :authenticate_secretary!, only: [:secretary_view]
    before_action :require_login
    def index
      @students = if params[:query].present?
                    Student.search(params[:query])
                  else
                    Student.all
                  end
  
      @students = @students.order(sort_column + " " + sort_direction)
    end
  
    def new
      @student = Student.new
    end
  
    def create
      @student = Student.find_by(email: student_params[:email])
      #sign_in_date = Date.today.beginning_of_day
      #added this
      @event = Event.find_by(date: DateTime.current.beginning_of_day)
      sign_in_date = Time.current
      #
      
      if @student 
        if find_student_attendance(@student, @event)
          redirect_to new_student_path, alert: "You have already signed in for this event."
        else
          increment_attendance_points(@student)
          update_student_info(@student, student_params)
          record_event_attendance(@student, @event, sign_in_date)
          redirect_to new_student_path, notice: "Student profile updated successfully."
        end
      else
        @student = Student.new(student_params)
        @student.attendance_points = 1
  
        if @student.save
          record_event_attendance(@student, @event, sign_in_date)
          redirect_to new_student_path, notice: "Student profile created successfully."
        else
          render :new
        end
      end
    end

    def find_student_attendance(student, event)
      EventAttendance.exists?(student: student, event: event)
    end

    def increment_attendance_points(student)
      student.attendance_points += 1
      student.save
    end

    def update_student_info(student, params)
      student.name = params[:name]
      student.year = params[:year]
      student.major = params[:major]
      student.save
    end

    def record_event_attendance(student, event, sign_in_date)
      EventAttendance.create(student: student, event: event, attended_on: sign_in_date)
    end
  
    def attendance
        @student = Student.find(params[:id])
        @events_attended = @student.events
    #   if @student
    #     @student.increment(:attendance_points)
    #     @student.events_attended = (@student.events_attended || []) << params[:event]
    #     @student.save
    #     render json: @student
    #   else
    #     @student = Student.new(name: params[:name], year: params[:year], email: params[:email], attendance_points: 1, events_attended: [params[:event]])
    #     if @student.save
    #       render json: @student, status: :created
    #     else
    #       render json: @student.errors, status: :unprocessable_entity
    #     end
    #   end
    end
  
    def secretary_view
      @students = Student.all
    end
  
    private

  def sort_column
    %w[name year email major attendance_points].include?(params[:sort]) ? params[:sort] : "major"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
  
    def student_params
      params.require(:student).permit(:name, :year, :email, :major, :id)
    end
  
    def authenticate_secretary!
      authenticate_or_request_with_http_basic do |username, password|
        username == 'secretary' && password == 'secret_password'
      end
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
        link_to title, { sort: column, direction: direction }
      end
    
      def sort_column
        %w[name year email major attendance_points].include?(params[:sort]) ? params[:sort] : "major"
      end
    
      def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
      end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Event Name</th>
      <th>Event Date</th>
      <th>Total Attendees</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date.strftime("%Y-%m-%d") %></td>
        <td><%= event.students.count %></td>
        <td><%= link_to 'View Attendees', event_path(event), class: 'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h2>Create New Event</h2>

<div class="container-fluid">

<%= form_with model: @event, local: true do |form| %>

  <div class="form-group">
    <%= form.label :name, "Event Name" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Event Name" %>
  </div>

  <div class="form-group">
    <%= form.label :date, "Event Date" %>
    <%= form.date_select :date, class: "form-control" %>
  </div>

  <%= form.submit "Create Event", class: "btn btn-outline-primary" %>
<% end %>

</div>

app/views/events/show.html.erb
<h1 class="text-center">Attendees for <%= @event.name %> on <%= @event.date.strftime("%Y-%m-%d") %></h1>

<h2>Attendees List</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Class Year</th>
      <th>Major</th>
      <th>Attended On</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.name %></td>
        <td><%= attendee.email %></td>
        <td><%= attendee.year %></td>
        <td><%= attendee.year %></td>
        <td><%= attendee.event_attendances.find_by(event: @event).attended_on.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td>
          <%= link_to 'View History', student_attendance_path(attendee), class: 'btn btn-outline-secondary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Events', events_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShpeSignIn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">


    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="<%= asset_path 'shpelogo.ico' %>" type="image/x-icon">
    <link rel="icon" href="<%= asset_path 'shpelogo.ico' %>" type="image/x-icon">
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= image_tag 'shpelogo.png', alt: 'SHPE Logo', width: '50', height: '50' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Students', students_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign In', new_student_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Events
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><%= link_to 'Event List', events_path, class: 'nav-link' %></a>
          <a class="dropdown-item"><%= link_to 'Create New Event', new_event_path, class: 'nav-link' %></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>
  <% flash.each do |key, message| %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
    <%= yield %>
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

app/views/students/attendance.html.erb
<div class="container">
        <h1 class="mt-5">Events Attended by <%= @student.name %></h1>
        <ul class="list-group mt-3">
            <% @events_attended.each do |event| %>
                <li class="list-group-item"><%= event.name %> (on <%= event.date %>)</li>
            <% end %>
        </ul>
</div>

app/views/students/index.html.erb
<div class="container-fluid">
<head>
  <h2>Students</h1>
  <%= form_with url: students_path, method: :get, local: true do %>
  <div class="input-group mb-3">
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search by name, email, or major" %>
    <div class="input-group-append">
      <%= submit_tag "Search", class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>
</head>

<style>
  a {
  color: rgb(109, 109, 109); /* Set text color to black */
  }
  h2 {
    text-align: center;
  }
</style>


<table class="table">
  <thead>
        <tr>
          <th><%= sortable "email", "Email" %></th>
          <th><%= sortable "name", "Name" %></th>
          <th><%= sortable "year", "Year" %></th>
          <th><%= sortable "major", "Major" %></th>
          <th><%= sortable "attendance_points", "Points" %></th>
          <th>Actions</th>
        </tr>
      </thead>
  <tbody>
    <% @students.each do |student| %>
      <% if student %>
        <tr>
          <td><%= student.email %></td>
          <td><%= student.name %></td>
          <td><%= student.year %></td>
          <td><%= student.major %></td>
          <td><%= student.attendance_points %></td>
          <td><%= link_to 'View History', student_attendance_path(student), class: 'btn btn-info' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/students/new.html.erb
<div class="container-fluid">
<%= form_with model: @student, local: true do |form| %>
  <div class="form-group">
    <%= form.label :email, "Email address" %>
    <%= form.email_field :email, class: "form-control", placeholder: "jjohn153@u.rochester.edu" %>
  </div>
  <div class="form-group">
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Jordan Johnson" %>
  </div>
  <div class="form-group">
    <%= form.label :year, "Year" %>
    <%= form.text_field :year, class: "form-control", placeholder: "2025", minlength: 4, maxlength: 4 %>
  </div>
  <div class="form-group">
    <%= form.label :major, "Major" %>
    <%= form.text_field :major, class: "form-control", placeholder: "Computer Science" %>
  </div>
  <%= form.submit "Submit", class: "btn btn-outline-secondary" %>
<% end %>
</div>